<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use Myth\Auth\Password;

class UmkmSeeder extends Seeder
{
    public function run()
    {
        helper('auth');

        $users = [
        [
            'id'               => 1001,
            'username'         => 'aiepon',
            'email'            => 'aieponaiepon@gmail.com',
            'fullname'         => 'Aiepon',
            'nama_umkm'        => 'Aiepon',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm101'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1002,
            'username'         => 'erlina',
            'email'            => 'Amarina834@gmail.com',
            'fullname'         => 'Erlina',
            'nama_umkm'        => 'Erlina Collection',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm102'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1003,
            'username'         => 'maryati',
            'email'            => 'Gheaalifa11@gmail.com',
            'fullname'         => 'Maryati',
            'nama_umkm'        => 'Alifa Handmade',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm103'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1004,
            'username'         => 'najla',
            'email'            => 'najlatarad@gmail.com',
            'fullname'         => 'Najla Tiara Diva',
            'nama_umkm'        => 'Dimsum & Es Teh By Najla',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm104'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1005,
            'username'         => 'nursyam',
            'email'            => 'nursyam1989@gmail.com',
            'fullname'         => 'Nursyam Permats Sari',
            'nama_umkm'        => 'Kedai Seblak Merona',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm105'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1006,
            'username'         => 'musyarofah',
            'email'            => 'Musyarofahoppe@gmail.com',
            'fullname'         => 'Musyarofah',
            'nama_umkm'        => 'Dapur Ope',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm106'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1007,
            'username'         => 'riskyanti',
            'email'            => 'arkia637@gmail.com',
            'fullname'         => 'Riskyanti',
            'nama_umkm'        => 'Zakia Crispy Chips',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm107'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1008,
            'username'         => 'shinta',
            'email'            => 'Shintanuranggraini23@gmail.com',
            'fullname'         => 'Shinta Nur Anggraini',
            'nama_umkm'        => 'Kedai Tujuan Coklat Kuwentel Slow Bar',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm108'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1009,
            'username'         => 'soimah',
            'email'            => 'soimah2975@gmail.com',
            'fullname'         => 'Soimah',
            'nama_umkm'        => 'Warung S. Pagi',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm109'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1010,
            'username'         => 'sriwahyuni',
            'email'            => 'juui201053@gmail.com',
            'fullname'         => 'Sri Wahyuni Rahmayanti',
            'nama_umkm'        => 'Dapo Maklong',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm110'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1011,
            'username'         => 'sriwulandari',
            'email'            => 'atributkampus@gmail.com',
            'fullname'         => 'Sri Wulandari',
            'nama_umkm'        => 'Cahaya Souvenir Depok',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm111'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1012,
            'username'         => 'ulan',
            'email'            => 'nathywulansari22@gmail.com',
            'fullname'         => 'Ulan / Nati Yulansari',
            'nama_umkm'        => 'Mino\'s Kitchen',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm112'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1013,
            'username'         => 'hendra',
            'email'            => 'homehendrahomene@gmail.com',
            'fullname'         => 'Hendra',
            'nama_umkm'        => 'Home Tjutjian Laundry',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm113'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1014,
            'username'         => 'meliawati',
            'email'            => 'liaheri993@gmail.com',
            'fullname'         => 'Meliawati',
            'nama_umkm'        => 'Kios Cudas Family Shakira',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm114'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1015,
            'username'         => 'mulyati',
            'email'            => 'mulyati141980@gmail.com',
            'fullname'         => 'Mulyati',
            'nama_umkm'        => 'Lapak Sarapan',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm115'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1016,
            'username'         => 'nining',
            'email'            => 'kantinjambumami@gmail.com',
            'fullname'         => 'Nining',
            'nama_umkm'        => 'Kantin Jambu',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm116'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1017,
            'username'         => 'maya',
            'email'            => 'mayafitri.rh@gmail.com',
            'fullname'         => 'Maya',
            'nama_umkm'        => 'Maya',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm117'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1018,
            'username'         => 'nurma',
            'email'            => 'batinmuma205@gmail.com',
            'fullname'         => 'Nurma',
            'nama_umkm'        => 'Nor\'mah Cake & Cookies',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm118'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1019,
            'username'         => 'romaneh',
            'email'            => 'romaneh69@gmail.com',
            'fullname'         => 'Romaneh',
            'nama_umkm'        => 'Dapur Kue Betawi Mpo Romaneh',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm119'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1020,
            'username'         => 'supiyati',
            'email'            => 'upin.supiyati@gmail.com',
            'fullname'         => 'Supiyati',
            'nama_umkm'        => 'Kedai Tebing',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm120'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1021,
            'username'         => 'wiwi',
            'email'            => 'dfirdaus1979@gmail.com',
            'fullname'         => 'Wiwi',
            'nama_umkm'        => 'Rafa Kitchen',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm121'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1022,
            'username'         => 'yulia',
            'email'            => 'youleea27@gmail.com',
            'fullname'         => 'Yulia Rahmi',
            'nama_umkm'        => 'Yulia',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm122'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
        [
            'id'               => 1023,
            'username'         => 'yuliani',
            'email'            => 'Yulialuliani553@gmail.com',
            'fullname'         => 'Yuliani',
            'nama_umkm'        => 'Ayam Geprek Edun Aneka Rica Bowl',
            'user_img'         => 'img/profile/default.jpg',
            'tipeakun'         => 1,
            'password_hash'    => Password::hash('umkm123'),
            'active'           => 1,
            'force_pass_reset' => 0,
            'created_at'       => date('Y-m-d H:i:s'),
            'updated_at'       => date('Y-m-d H:i:s'),
        ],
    ];

        // Hapus semua UMKM lama
        $this->db->table('auth_groups_users')->where('group_id', 2)->delete();
        $this->db->table('users')->where('id >=', 1001)->where('id <=', 1023)->delete();

        // Insert user baru
        $this->db->table('users')->insertBatch($users);

        // Masukkan ke grup UMKM (group_id = 2)
        $groups = [];

        foreach ($users as $user) {
            $groups[] = [
                'group_id' => 2,
                'user_id'  => $user['id'],
            ];
        }

        $this->db->table('auth_groups_users')->insertBatch($groups);
    }
}
